### PR TITLE
Fix site parameter not being set during addon matching process

### LINKED ISSUE #2: Bug in update.lua: doesn't remember all addons
_Edit: Actually it's the case for all of them. I had ignored Details previously, after unignoring the same thing happens here._

---

I am using some addons to test update.lua. After going through all and matching/ignoring them, some of them don't seem to be remembered.
In my case, that's **BugSack**, **!BugGrabber** and **AdiBags**.
Every time I run `lua update.lua` he tells me that he's found them anew. They do get saved in db.lua though:
```
	["AdiBags"] = {
		["version"] = "v1.9.8";
		["dir"] = "AdiBags";
		["id"] = "adibags";
		["author"] = "Adirelle";
		["title"] = "AdiBags";
		["wow"] = "70300";
	};
```

Same behaviour with Lua 5.1 and 5.3.4

My addons:
addons

### PR DESCRIPTION
**Pull request by jukx**
Should fix #2

### CODE REVIEW

**Comment by Phanx** [comment]
Since we already know the site based on which parsing function we're in, I don't see a reason to pass around an extra argument; just hardcode the appropriate site name in each parsing function.

**Comment by jukx** [comment]
Ideally I would rewrite the whole thing so you'd just pass the sitename once, but for now I think this is passable.
I really don't like repeating the site identifiers here. This is just messy when you consider typos and such.
Also you'd have to find a workaround for the wowace case since it just uses the curseforge function.

**Comment by jukx** [comment]
Btw, now that I look at it, the wowinterface function seems non-functional. It doesn't actually append anything to the table.

**Comment by Phanx** [comment]
It's been a while since I actually used it, but I'm pretty sure the WoWI parser only sees the latest version right now, and the parsing of other versions (all the table rows in the HTML) doesn't work but I never got around to fixing it.

**Comment by Phanx** [comment]
Passing the site name around as a function argument felt too dirty.

WoWI search result parsing will be addressed separately.

**Pull request closed without merging**
